services:
  - type: web
    name: thai-language-toolkit
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run apps/streamlit_app.py --server.port $PORT --server.address 0.0.0.0"
    plan: free